arby: com::saxbophone::arby::Uint Class Reference
com::saxbophone::arby::Uint Class Reference
Arbitrary-precision unsigned integer type.
#include <arby.hpp>
Public Member Functions
constexpr bool operator== (const Uint &rhs) const =default
Defaulted equality operator for Uint objects.
constexpr auto operator<=> (const Uint &rhs) const
three-way-comparison operator defines all relational operators
constexpr Uint ()
Default constructor, initialises to numeric value 0
constexpr Uint (uintmax_t value)
Integer-constructor, initialises with the given integer value.
Uint (std::string digits)
String-constructor, initialises from string decimal value.
constexpr operator uintmax_t () const
constexpr operator long double () const
operator std::string () const
constexpr Uint & operator++ ()
prefix increment
constexpr Uint operator++ (int)
postfix increment
constexpr Uint & operator-- ()
prefix decrement
constexpr Uint operator-- (int)
postfix decrement
constexpr Uint & operator+= (Uint rhs)
addition-assignment
constexpr Uint & operator-= (Uint rhs)
subtraction-assignment
constexpr Uint & operator*= (const Uint &rhs)
multiplication-assignment
constexpr Uint & operator/= (const Uint &rhs)
division-assignment
constexpr Uint & operator%= (const Uint &rhs)
modulo-assignment
constexpr operator bool () const
contextual conversion to bool (behaves same way as int)
Static Public Member Functions
static Uint from_float (long double value)
Constructor-like static method, creates Uint from floating point value.
static constexpr std::tuple< Uint, Uint > divmod (const Uint &lhs, const Uint &rhs)
division and modulo all-in-one, equivalent to C/C++ div() and Python divmod()
static constexpr Uint pow (const Uint &base, const Uint &exponent)
Static Public Attributes
static constexpr int BASE = (int)std::numeric_limits<StorageType>::max() + 1
The number base used internally to store the value.
Friends
std::ostream & operator<< (std::ostream &os, const Uint &object)
custom ostream operator that allows this class to be printed with std::cout and friends
constexpr friend Uint operator+ (Uint lhs, const Uint &rhs)
Addition operator for Uint.
constexpr friend Uint operator- (Uint lhs, const Uint &rhs)
Subtraction operator for Uint.
constexpr friend Uint operator* (const Uint &lhs, const Uint &rhs)
Multiplication operator for Uint.
constexpr friend Uint operator/ (Uint lhs, const Uint &rhs)
Division operator for Uint.
constexpr friend Uint operator% (Uint lhs, const Uint &rhs)
Modulo operator for Uint.
Detailed Description
Arbitrary-precision unsigned integer type.
Note
std::numeric_limits<Uint> is specialised such that most of the members of that type are implemented to describe the traits of this type.
Exceptions include any members of std::numeric_limits<> which describe a finite number of digits or a maximmum value, neither of which apply to this type as it is unbounded.
Exceptions
std::logic_error may be thrown from most methods when the result of an operation leaves a Uint object with leading zero digits in its internal representation. Such cases are the result of bugs in this code and should be reported as such.
Constructor & Destructor Documentation
Uint() [1/2]
constexpr com::saxbophone::arby::Uint::Uint (uintmax_t value) inline constexpr
Integer-constructor, initialises with the given integer value.
Parameters
value value to initialise with
References BASE.
Uint() [2/2]
com::saxbophone::arby::Uint::Uint (std::string digits)
String-constructor, initialises from string decimal value.
Parameters
digits string containing the digits of the value to initialise with, written in decimal
Warning
Unimplemented
Member Function Documentation
divmod()
static constexpr std::tuple<Uint, Uint> com::saxbophone::arby::Uint::divmod (const Uint & lhs, const Uint & rhs) inline static constexpr
division and modulo all-in-one, equivalent to C/C++ div() and Python divmod()
Parameters
lhs,rhs operands for the division/modulo operation
Returns
tuple of {quotient, remainder}
Exceptions
std::domain_error when rhs is zero
Referenced by pow().
from_float()
static Uint com::saxbophone::arby::Uint::from_float (long double value) inline static
Constructor-like static method, creates Uint from floating point value.
Returns
Uint with the value of the given float, with the fractional part truncated off
Parameters
value Positive floating point value to initialise with
Exceptions
std::domain_error when value < 0 or when value is not a finite number.
References BASE.
operator bool()
constexpr com::saxbophone::arby::Uint::operator bool () const inline explicit constexpr
contextual conversion to bool (behaves same way as int)
Returns
false when value is 0, otherwise true
operator long double()
constexpr com::saxbophone::arby::Uint::operator long double () const inline explicit constexpr
Returns
Value of this Uint object cast to long long double
operator std::string()
com::saxbophone::arby::Uint::operator std::string () const explicit
Returns
string representing the value of this Uint, in decimal
operator uintmax_t()
constexpr com::saxbophone::arby::Uint::operator uintmax_t () const inline explicit constexpr
Returns
Value of this Uint object cast to uintmax_t
Exceptions
std::range_error when Uint value is out of range for uintmax_t
operator%=()
constexpr Uint& com::saxbophone::arby::Uint::operator%= (const Uint & rhs) inline constexpr
modulo-assignment
Modulo-divides this Uint by other value and stores result to this
Note
This returns the modulo/remainder of the division operation
Parameters
rhs value to modulo-divide this Uint by
Returns
resulting object after modulo-assignment
Exceptions
std::domain_error when rhs is zero
operator*=()
constexpr Uint& com::saxbophone::arby::Uint::operator*= (const Uint & rhs) inline constexpr
multiplication-assignment
Multiplies this Uint by other value and assigns the result to self
Parameters
rhs value to multiply this Uint by
Returns
resulting object after multiplication-assignment
operator++() [1/2]
constexpr Uint& com::saxbophone::arby::Uint::operator++ () inline constexpr
prefix increment
Returns
new value of Uint object after incrementing
Referenced by operator++().
operator++() [2/2]
constexpr Uint com::saxbophone::arby::Uint::operator++ (int) inline constexpr
postfix increment
Returns
old value of Uint object before incrementing
References operator++().
operator+=()
constexpr Uint& com::saxbophone::arby::Uint::operator+= (Uint rhs) inline constexpr
addition-assignment
Adds other value to this Uint and assigns the result to self
Parameters
rhs value to add to this Uint
Returns
resulting object after addition-assignment
operator--() [1/2]
constexpr Uint& com::saxbophone::arby::Uint::operator-- () inline constexpr
prefix decrement
Returns
new value of Uint object after decrementing
Exceptions
std::underflow_error when value of Uint is 0
Referenced by operator--().
operator--() [2/2]
constexpr Uint com::saxbophone::arby::Uint::operator-- (int) inline constexpr
postfix decrement
Returns
old value of Uint object before decrementing
Exceptions
std::underflow_error when value of Uint is 0
References operator--().
operator-=()
constexpr Uint& com::saxbophone::arby::Uint::operator-= (Uint rhs) inline constexpr
subtraction-assignment
Subtracts other value from this Uint and assigns the result to self
Parameters
rhs value to subtract from this Uint
Returns
resulting object after subtraction-assignment
Exceptions
std::underflow_error when rhs is bigger than this
operator/=()
constexpr Uint& com::saxbophone::arby::Uint::operator/= (const Uint & rhs) inline constexpr
division-assignment
Divides this Uint by other value and stores result to this
Note
This implements floor-division, returning the quotient only
Parameters
rhs value to divide this Uint by
Returns
resulting object after division-assignment
Exceptions
std::domain_error when rhs is zero
operator<=>()
constexpr auto com::saxbophone::arby::Uint::operator<=> (const Uint & rhs) const inline constexpr
three-way-comparison operator defines all relational operators
Parameters
rhs other Uint object to compare against
Returns
std::strong_ordering object for comparison
operator==()
constexpr bool com::saxbophone::arby::Uint::operator== (const Uint & rhs) const constexpr default
Defaulted equality operator for Uint objects.
Parameters
rhs other Uint object to compare against
Returns
true if objects are equal, otherwise false
pow()
static constexpr Uint com::saxbophone::arby::Uint::pow (const Uint & base, const Uint & exponent) inline static constexpr
Returns
base raised to the power of exponent
Parameters
base,exponent parameters for the base and exponent
References divmod().
Referenced by com::saxbophone::arby::operator""_uarb().
Friends And Related Function Documentation
operator%
constexpr friend Uint operator% (Uint lhs, const Uint & rhs) friend
Modulo operator for Uint.
Note
This implements modulo-division, returning the remainder only
Parameters
lhs,rhs operands for the division
Returns
remainder of lhs / rhs
Exceptions
std::domain_error when rhs is zero
operator*
constexpr friend Uint operator* (const Uint & lhs, const Uint & rhs) friend
Multiplication operator for Uint.
Parameters
lhs,rhs operands for the multiplication
Returns
product of lhs * rhs
operator+
constexpr friend Uint operator+ (Uint lhs, const Uint & rhs) friend
Addition operator for Uint.
Parameters
lhs,rhs operands for the addition
Returns
sum of lhs + rhs
operator-
constexpr friend Uint operator- (Uint lhs, const Uint & rhs) friend
Subtraction operator for Uint.
Parameters
lhs,rhs operands for the subtraction
Returns
result of lhs - rhs
Exceptions
std::underflow_error when rhs is bigger than lhs
operator/
constexpr friend Uint operator/ (Uint lhs, const Uint & rhs) friend
Division operator for Uint.
Note
This implements floor-division, returning the quotient only
Parameters
lhs,rhs operands for the division
Returns
quotient of lhs / rhs
operator<<
std::ostream& operator<< (std::ostream & os, const Uint & object) friend
custom ostream operator that allows this class to be printed with std::cout and friends
Parameters
os stream to output to
object Uint to print
Member Data Documentation
BASE
constexpr int com::saxbophone::arby::Uint::BASE = (int)std::numeric_limits<StorageType>::max() + 1 static constexpr
The number base used internally to store the value.
This is the radix that the digits are encoded in
Referenced by from_float(), and Uint().
The documentation for this class was generated from the following files:
arby/include/arby/arby.hpp
arby/src/arby.cpp