arby: com::saxbophone::arby::Nat Class Reference
com::saxbophone::arby::Nat Class Reference
Arbitrary-precision unsigned integer type.
#include <Nat.hpp>
Public Types
using StorageType = PRIVATE::StorageTraits::StorageType
The type used to store the digits of this Nat object.
using OverflowType = PRIVATE::StorageTraits::OverflowType
This is the smallest type guaranteed to be able to store the result of any product or sum of two values of the type used to store the number's digits.
Public Member Functions
constexpr bool operator== (const Nat &rhs) const =default
Defaulted equality operator for Nat objects.
constexpr auto operator<=> (const Nat &rhs) const
three-way-comparison operator defines all relational operators
constexpr Nat ()
Default constructor, initialises to numeric value 0
constexpr Nat (uintmax_t value)
Integer-constructor, initialises with the given integer value.
template<template< typename... > class Container, typename... Ts>
constexpr Nat (const Container< StorageType, Ts... > &digits)
Digits-constructor, initialises Nat using the given digits.
constexpr Nat (const codlili::list< StorageType > &digits)
constexpr Nat (std::initializer_list< StorageType > digits)
Nat (std::string digits)
String-constructor, initialises from string decimal value.
constexpr operator uintmax_t () const
constexpr operator long double () const
constexpr operator float () const
constexpr operator double () const
template<typename To >
constexpr operator To () const
operator std::string () const
constexpr Nat & operator++ ()
prefix increment
constexpr Nat operator++ (int)
postfix increment
constexpr Nat & operator-- ()
prefix decrement
constexpr Nat operator-- (int)
postfix decrement
constexpr Nat & operator+= (Nat rhs)
addition-assignment
constexpr Nat & operator-= (Nat rhs)
subtraction-assignment
constexpr Nat & operator*= (const Nat &rhs)
multiplication-assignment
constexpr Nat & operator/= (const Nat &rhs)
division-assignment
constexpr Nat & operator%= (const Nat &rhs)
modulo-assignment
constexpr Nat & operator|= (const Nat &rhs)
bitwise OR-assignment
constexpr Nat & operator&= (const Nat &rhs)
bitwise AND-assignment
constexpr Nat & operator^= (const Nat &rhs)
bitwise XOR-assignment
constexpr operator bool () const
contextual conversion to bool (behaves same way as int)
constexpr std::size_t digit_length () const
constexpr std::size_t byte_length () const
constexpr std::size_t bit_length () const
constexpr codlili::list< StorageType > digits () const
Static Public Member Functions
static Nat from_float (long double value)
Constructor-like static method, creates Nat from floating point value.
static constexpr std::pair< Nat, Nat > divmod (const Nat &lhs, const Nat &rhs)
division and modulo all-in-one, equivalent to C/C++ div() and Python divmod()
Static Public Attributes
static constexpr OverflowType BASE = (OverflowType)std::numeric_limits<StorageType>::max() + 1
The number base used internally to store the value.
Friends
std::ostream & operator<< (std::ostream &os, const Nat &object)
custom ostream operator that allows class Nat to be printed with std::cout and friends
constexpr friend Nat operator+ (Nat lhs, const Nat &rhs)
Addition operator for Nat.
constexpr friend Nat operator- (Nat lhs, const Nat &rhs)
Subtraction operator for Nat.
constexpr friend Nat operator* (const Nat &lhs, const Nat &rhs)
Multiplication operator for Nat.
constexpr friend Nat operator/ (Nat lhs, const Nat &rhs)
Division operator for Nat.
constexpr friend Nat operator% (Nat lhs, const Nat &rhs)
Modulo operator for Nat.
constexpr friend Nat operator| (Nat lhs, const Nat &rhs)
bitwise OR operator for Nat
constexpr friend Nat operator& (Nat lhs, const Nat &rhs)
bitwise AND operator for Nat
constexpr friend Nat operator^ (Nat lhs, const Nat &rhs)
bitwise XOR operator for Nat
Related Functions
(Note that these are not member functions.)
constexpr Nat pow (const Nat &base, const Nat &exponent)
constexpr std::pair< Nat, Nat > ilog (const Nat &base, const Nat &x)
Calculates integer log of x in base as bounds of \(log_b(x)\).
constexpr Nat operator""_nat (const char *literal)
raw user-defined-literal for Nat class
Detailed Description
Arbitrary-precision unsigned integer type.
This is named after \(\mathbb{N}\), the set of Natural numbers, which this type models
Note
std::numeric_limits<Nat> is specialised such that most of the members of that type are implemented to describe the traits of this type.
Exceptions include any members of std::numeric_limits<> which describe a finite number of digits or a maximmum value, neither of which apply to this type as it is unbounded.
Exceptions
std::logic_error may be thrown from most methods when the result of an operation leaves a Nat object with leading zero digits in its internal representation. Such cases are the result of bugs in this code and should be reported as such.
Member Typedef Documentation
OverflowType
using com::saxbophone::arby::Nat::OverflowType = PRIVATE::StorageTraits::OverflowType
This is the smallest type guaranteed to be able to store the result of any product or sum of two values of the type used to store the number's digits.
Note
Consequently, this is the type used to represent Nat::BASE as that value is +1 beyond the upper bound for the type used to store the digits.
StorageType
using com::saxbophone::arby::Nat::StorageType = PRIVATE::StorageTraits::StorageType
The type used to store the digits of this Nat object.
Note
The exact native type used for this is platform-specific:
Normally, it is the same as unsigned int
However, in the unlikely event that unsigned int is not smaller than uintmax_t, we pick the next smaller type (typically unsigned short)
Constructor & Destructor Documentation
Nat() [1/5]
constexpr com::saxbophone::arby::Nat::Nat (uintmax_t value) inline constexpr
Integer-constructor, initialises with the given integer value.
Parameters
value value to initialise with
Nat() [2/5]
template<template< typename... > class Container, typename... Ts> constexpr com::saxbophone::arby::Nat::Nat (const Container< StorageType, Ts... > & digits) inline constexpr
Digits-constructor, initialises Nat using the given digits.
Template Parameters
Container A container type exposing an STL-like API that provides begin(), end(), and empty() at a minimum
Parameters
digits the digits to initialise the Nat object from, these should be encoded in base Nat::BASE (this corresponds to max StorageType value)
Precondition
digits is not empty
Exceptions
std::invalid_argument when digits is empty
References digits().
Nat() [3/5]
constexpr com::saxbophone::arby::Nat::Nat (const codlili::list< StorageType > & digits) inline constexpr
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Remarks
Overload for constructing from codlili::list of digits
References digits().
Nat() [4/5]
constexpr com::saxbophone::arby::Nat::Nat (std::initializer_list< StorageType > digits) inline constexpr
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Remarks
Overload for constructing from std::initializer_list of digits
References digits().
Nat() [5/5]
com::saxbophone::arby::Nat::Nat (std::string digits)
String-constructor, initialises from string decimal value.
Parameters
digits string containing the digits of the value to initialise with, written in decimal
Member Function Documentation
bit_length()
constexpr std::size_t com::saxbophone::arby::Nat::bit_length () const inline constexpr
Returns
size by number of bits needed to store the number's value
Note
this can be less than \(bytes \times 8 \)
byte_length()
constexpr std::size_t com::saxbophone::arby::Nat::byte_length () const inline constexpr
Returns
size by number of bytes needed to store the number's digits
Note
this can be less than \(digits \times sizeof(digit) \)
digit_length()
constexpr std::size_t com::saxbophone::arby::Nat::digit_length () const inline constexpr
Returns
size by number of digits
digits()
constexpr codlili::list<StorageType> com::saxbophone::arby::Nat::digits () const inline constexpr
Returns
a copy of the underlying digits that make up this Nat value
Referenced by Nat().
divmod()
static constexpr std::pair<Nat, Nat> com::saxbophone::arby::Nat::divmod (const Nat & lhs, const Nat & rhs) inline static constexpr
division and modulo all-in-one, equivalent to C/C++ div() and Python divmod()
Parameters
lhs,rhs operands for the division/modulo operation
Returns
pair of {quotient, remainder}
Exceptions
std::domain_error when rhs is zero
Todo:
Work out time-complexity
Referenced by pow().
from_float()
static Nat com::saxbophone::arby::Nat::from_float (long double value) inline static
Constructor-like static method, creates Nat from floating point value.
Returns
Nat with the value of the given float, with the fractional part truncated off
Parameters
value Positive floating point value to initialise with
Exceptions
std::domain_error when value < 0 or when value is not a finite number.
References BASE.
operator bool()
constexpr com::saxbophone::arby::Nat::operator bool () const inline explicit constexpr
contextual conversion to bool (behaves same way as int)
Returns
false when value is 0, otherwise true
Note
Complexity: \(\mathcal{O(1)} \)
operator double()
constexpr com::saxbophone::arby::Nat::operator double () const inline explicit constexpr
Returns
Value of this Nat object cast to double
operator float()
constexpr com::saxbophone::arby::Nat::operator float () const inline explicit constexpr
Returns
Value of this Nat object cast to float
operator long double()
constexpr com::saxbophone::arby::Nat::operator long double () const inline explicit constexpr
Returns
Value of this Nat object cast to long double
operator std::string()
com::saxbophone::arby::Nat::operator std::string () const explicit
Returns
string representing the value of this Nat, in decimal
operator To()
template<typename To > constexpr com::saxbophone::arby::Nat::operator To () const inline explicit constexpr
Returns
Value of this Nat object cast to any numeric type
Template Parameters
To The data type to cast to
References BASE.
operator uintmax_t()
constexpr com::saxbophone::arby::Nat::operator uintmax_t () const inline explicit constexpr
Returns
Value of this Nat object cast to uintmax_t
Exceptions
std::range_error when Nat value is out of range for uintmax_t
operator%=()
constexpr Nat& com::saxbophone::arby::Nat::operator%= (const Nat & rhs) inline constexpr
modulo-assignment
Modulo-divides this Nat by other value and stores result to this
Note
This returns the modulo/remainder of the division operation
Parameters
rhs value to modulo-divide this Nat by
Returns
resulting object after modulo-assignment
Exceptions
std::domain_error when rhs is zero
Todo:
Work out time-complexity
operator&=()
constexpr Nat& com::saxbophone::arby::Nat::operator&= (const Nat & rhs) inline constexpr
bitwise AND-assignment
Note
Complexity: \(\mathcal{O(n)} \)
operator*=()
constexpr Nat& com::saxbophone::arby::Nat::operator*= (const Nat & rhs) inline constexpr
multiplication-assignment
Multiplies this Nat by other value and assigns the result to self
Parameters
rhs value to multiply this Nat by
Returns
resulting object after multiplication-assignment
Note
Complexity: \(\mathcal{O(n^2)} \)
operator++() [1/2]
constexpr Nat& com::saxbophone::arby::Nat::operator++ () inline constexpr
prefix increment
Returns
new value of Nat object after incrementing
Note
Best-case complexity: \(\mathcal{O(1)} \)
Worst-case complexity: \(\mathcal{O(n)} \)
Referenced by operator++().
operator++() [2/2]
constexpr Nat com::saxbophone::arby::Nat::operator++ (int) inline constexpr
postfix increment
Returns
old value of Nat object before incrementing
Note
Best-case complexity: \(\mathcal{O(1)} \)
Worst-case complexity: \(\mathcal{O(n)} \)
References operator++().
operator+=()
constexpr Nat& com::saxbophone::arby::Nat::operator+= (Nat rhs) inline constexpr
addition-assignment
Adds other value to this Nat and assigns the result to self
Parameters
rhs value to add to this Nat
Returns
resulting object after addition-assignment
Note
Complexity: \(\mathcal{O(n)} \)
operator--() [1/2]
constexpr Nat& com::saxbophone::arby::Nat::operator-- () inline constexpr
prefix decrement
Returns
new value of Nat object after decrementing
Exceptions
std::underflow_error when value of Nat is 0
Note
Best-case complexity: \(\mathcal{O(1)} \)
Worst-case complexity: \(\mathcal{O(n)} \)
Referenced by operator--().
operator--() [2/2]
constexpr Nat com::saxbophone::arby::Nat::operator-- (int) inline constexpr
postfix decrement
Returns
old value of Nat object before decrementing
Exceptions
std::underflow_error when value of Nat is 0
Note
Best-case complexity: \(\mathcal{O(1)} \)
Worst-case complexity: \(\mathcal{O(n)} \)
References operator--().
operator-=()
constexpr Nat& com::saxbophone::arby::Nat::operator-= (Nat rhs) inline constexpr
subtraction-assignment
Subtracts other value from this Nat and assigns the result to self
Parameters
rhs value to subtract from this Nat
Returns
resulting object after subtraction-assignment
Exceptions
std::underflow_error when rhs is bigger than this
Note
Complexity: \(\mathcal{O(n)} \)
operator/=()
constexpr Nat& com::saxbophone::arby::Nat::operator/= (const Nat & rhs) inline constexpr
division-assignment
Divides this Nat by other value and stores result to this
Note
This implements floor-division, returning the quotient only
Parameters
rhs value to divide this Nat by
Returns
resulting object after division-assignment
Exceptions
std::domain_error when rhs is zero
Todo:
Work out time-complexity
operator<=>()
constexpr auto com::saxbophone::arby::Nat::operator<=> (const Nat & rhs) const inline constexpr
three-way-comparison operator defines all relational operators
Parameters
rhs other Nat object to compare against
Returns
std::strong_ordering object for comparison
Note
Complexity: \(\mathcal{O(n)} \)
operator==()
constexpr bool com::saxbophone::arby::Nat::operator== (const Nat & rhs) const constexpr default
Defaulted equality operator for Nat objects.
Parameters
rhs other Nat object to compare against
Returns
true if objects are equal, otherwise false
Note
Worst-case complexity: \(\mathcal{O(n)} \)
operator^=()
constexpr Nat& com::saxbophone::arby::Nat::operator^= (const Nat & rhs) inline constexpr
bitwise XOR-assignment
Note
Complexity: \(\mathcal{O(n)} \)
operator|=()
constexpr Nat& com::saxbophone::arby::Nat::operator|= (const Nat & rhs) inline constexpr
bitwise OR-assignment
Note
Complexity: \(\mathcal{O(n)} \)
Friends And Related Function Documentation
ilog()
constexpr std::pair< Nat, Nat > ilog (const Nat & base, const Nat & x) related
Calculates integer log of x in base as bounds of \(log_b(x)\).
auto [low, high] = ilog(b, x);
Parameters
base base to use for \(b\)
x value to use for \(x\)
Precondition
\(b\geq2\)
\(x\geq1\)
Exceptions
std::domain_error when preconditions are violated
Returns
pair of \((low, high)\) where for \(\mathbb{R}\ v = log_b(x)\):
\(low = floor(v)\)
\(high = ceil(v)\)
Postcondition
\(low \leq high\)
Remarks
When \(low = high\):
\(log_b(x)\in\mathbb{N}\)
Otherwise:
\(log_b(x)\in\mathbb{R}\)
Note
Complexity: \(\mathcal{O}(n^2log(n)) \)
operator""_nat()
constexpr Nat operator""_nat (const char * literal) related
raw user-defined-literal for Nat class
Parameters
literal the literal
Returns
Corresponding arby::Nat value
Note
we use a raw literal in this case because as the Nat type is unbounded, we want to support a potentially infinite number of digits, or certainly more than can be stored in unsigned long long...
operator%
constexpr friend Nat operator% (Nat lhs, const Nat & rhs) friend
Modulo operator for Nat.
Note
This implements modulo-division, returning the remainder only
Parameters
lhs,rhs operands for the division
Returns
remainder of lhs / rhs
Exceptions
std::domain_error when rhs is zero
Todo:
Work out time-complexity
operator&
constexpr friend Nat operator& (Nat lhs, const Nat & rhs) friend
bitwise AND operator for Nat
Note
Complexity: \(\mathcal{O(n)} \)
operator*
constexpr friend Nat operator* (const Nat & lhs, const Nat & rhs) friend
Multiplication operator for Nat.
Parameters
lhs,rhs operands for the multiplication
Returns
product of lhs * rhs
Note
Complexity: \(\mathcal{O(n^2)} \)
operator+
constexpr friend Nat operator+ (Nat lhs, const Nat & rhs) friend
Addition operator for Nat.
Parameters
lhs,rhs operands for the addition
Returns
sum of lhs + rhs
Note
Complexity: \(\mathcal{O(n)} \)
operator-
constexpr friend Nat operator- (Nat lhs, const Nat & rhs) friend
Subtraction operator for Nat.
Parameters
lhs,rhs operands for the subtraction
Returns
result of lhs - rhs
Exceptions
std::underflow_error when rhs is bigger than lhs
Note
Complexity: \(\mathcal{O(n)} \)
operator/
constexpr friend Nat operator/ (Nat lhs, const Nat & rhs) friend
Division operator for Nat.
Note
This implements floor-division, returning the quotient only
Parameters
lhs,rhs operands for the division
Returns
quotient of lhs / rhs
Todo:
Work out time-complexity
operator<<
std::ostream& operator<< (std::ostream & os, const Nat & object) friend
custom ostream operator that allows class Nat to be printed with std::cout and friends
Note
Complexity is \(\mathcal{O(terrible)} \)
See also
std::ostream& Nat::operator<<(std::ostream& os, const Nat& object)
operator^
constexpr friend Nat operator^ (Nat lhs, const Nat & rhs) friend
bitwise XOR operator for Nat
Note
Complexity: \(\mathcal{O(n)} \)
operator|
constexpr friend Nat operator| (Nat lhs, const Nat & rhs) friend
bitwise OR operator for Nat
Note
Complexity: \(\mathcal{O(n)} \)
pow()
constexpr Nat pow (const Nat & base, const Nat & exponent) related
Returns
base raised to the power of exponent i.e. for base as \(b\) and exponent as \(x\): \(b^x\)
Parameters
base,exponent parameters for the base and exponent
Todo:
Work out time-complexity
References divmod(), and com::saxbophone::arby::pow().
Member Data Documentation
BASE
constexpr OverflowType com::saxbophone::arby::Nat::BASE = (OverflowType)std::numeric_limits<StorageType>::max() + 1 static constexpr
The number base used internally to store the value.
This is the radix that the digits are encoded in
Referenced by from_float(), and operator To().
The documentation for this class was generated from the following files:
arby/include/arby/Nat.hpp
arby/include/arby/math.hpp
arby/src/Nat.cpp